# version: '3.8'

# services:
#   db:
#     image: postgres:15
#     container_name: db
#     restart: always
#     env_file: .env
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: auth_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   redis:
#     image: redis:latest
#     container_name: redis-cache
#     restart: always
#     ports:
#       - "6379:6379"

#   rabbitmq:
#     image: rabbitmq:3-management
#     container_name: rabbitmq
#     restart: always
#     ports:
#       - "5672:5672"
#       - "15672:15672"

#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
#     container_name: elasticsearch
#     restart: always
#     environment:
#       - discovery.type=single-node
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#       - "xpack.security.enabled=false"  # If you don't need security
#       - "xpack.security.transport.ssl.enabled=false"  # Disable SSL/TLS for transport layer
#     ports:
#       - "9200:9200"
#       - "9300:9300"
#     volumes:
#       - es_data:/usr/share/elasticsearch/data

#   otel-collector:
#     image: otel/opentelemetry-collector-contrib:latest
#     container_name: otel-collector
#     restart: always
#     volumes:
#       - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
#     command: ["--config=/etc/otel-collector-config.yaml"]
#     ports:
#       - "4317:4317"
#       - "4318:4318"

#   kibana:
#     image: docker.elastic.co/kibana/kibana:8.10.2
#     container_name: kibana
#     restart: always
#     environment:
#       ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
#     ports:
#       - "5601:5601"

#   prometheus:
#     image: prom/prometheus:v2.39.0
#     container_name: prometheus
#     restart: always
#     ports:
#       - "9090:9090"
#     volumes:
#       - ./prometheus.yml:/etc/prometheus/prometheus.yml

#   grafana:
#     image: grafana/grafana:8.3.0
#     container_name: grafana
#     restart: always
#     ports:
#       - "3000:3000"
#     environment:
#       GF_SECURITY_ADMIN_PASSWORD: "admin"  # Set Grafana admin password
#     volumes:
#       - grafana_data:/var/lib/grafana

#   jaeger:
#     image: jaegertracing/all-in-one:1.30
#     container_name: jaeger
#     restart: always
#     ports:
#       - "5775:5775"
#       - "6831:6831/udp"
#       - "6832:6832/udp"
#       - "5778:5778"
#       - "16686:16686"  # Jaeger UI
#       - "14250:14250"
#       - "14268:14268"
#       - "9411:9411"

# volumes:
#   postgres_data:
#   es_data:
#   grafana_data:


version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    ports:
      - "5775:5775"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"  # If you don't need security
      - "xpack.security.transport.ssl.enabled=false"  # Disable SSL/TLS for transport layer
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  es_data:
  prometheus_data:
  grafana_data:
