version: '3.8'

services:
  authPostgres:
    container_name: dbserver_auth_postgres_container
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./auth/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./auth/seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  pg_data:
