version: '3.8'

services:
  postgres:
    container_name: "auth_postgres_container"
    image: "postgres:latest"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "mydatabase"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    container_name: "auth_redis_container"
    image: "redis:latest"
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: "password"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
